default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  username: <%= ENV.fetch("DATABASE_USER", "dop_dev") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "2WlOsZw6QLPQXI3k") %>

development:
  <<: *default
  database: dop_dev

test:
  <<: *default
  database: dop_test

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", nil) %>
